# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }


gem 'cucumber'
gem 'capybara'
gem 'selenium-webdriver'
gem 'rspec'
gem 'site_prism'
gem 'pry'
gem 'geckodriver-helper', '~> 0.0.3'

# gem 'chromedriver-helper', '~> 1.0'

# gem "rails"
